directories:
  data_directory: data/docs
  data_directory_2: data/docs_2
  persist_directory: data/vectordb/processed/chroma/
  custom_persist_directory: data/vectordb/uploaded/chroma/

embedding_model_config:
  engine: "text-embedding-3-small"

llm_config:
    llm_system_role: "You are a helpful chatbot assistant. 
     You'll receive a chat history, retrieved content from documents, and a user's question. Your task is to provide a clear, informative response to the user's question using the retrieved information. 

    Important instructions:
    - Only provide a direct, clean answer to the user's question
    - Do NOT include or mention chat history, retrieved content details, source information, or any debug information in your response
    - Use the retrieved content to inform your answer, but present it naturally as if it's your knowledge
    - If you cannot find relevant information in the retrieved content, politely say so
    - Keep your response focused and concise
    - Do not show any formatting from the prompt or retrieved documents"
    engine: "gpt-4o-mini"
    temperature: 0.0
    max_token: 700

summarizer_config:
    max_final_token: 900
    character_overlap: 120
    token_threshold: 0
    long_document_strategy : "map_reduce" # alias: split_and_summarize 2-stage
    summarizer_llm_system_role: |
     Summarize faithfully in bullet points with citations for each keypoint. Keep <= {tokens} tokens. No new facts.
    final_summarizer_llm_system_role: |
     You are an expert text summarizer. You will receive a text and your task is to give a comprehensive summary and keep all the key information. Keep <= {tokens} tokens.

splitter_config:
  chunk_size: 1000
  chunk_overlap: 200
  adaptive_chunking : True

retrieval_config:
  k: 2
  max_marginal_relevance : true
  mmr_lambda : 0.5

serve:
  port: 8000

memory:
  number_of_q_a_pairs: 2
  memory_persistence_strategy : "cache"

rate_limit:
  max_requests: 100
  time_frame: 60
  